name: Run Cron Jobs

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        sudo apt-get update && sudo apt-get install -y jq  # 安装 JSON 处理工具

    # 新增步骤：从 URL 获取 ACCOUNTS_JSON
    - name: Fetch ACCOUNTS_JSON
      run: |
        JSON_CONTENT=$(curl -s https://raw.gyyst.eu.org/gyyst/myprivate/refs/heads/main/serv00/serv00cf%E4%BF%9D%E6%B4%BBcron.json?token=${{ secrets.TOKEN }})  # 替换为实际 URL
        echo "ACCOUNTS_JSON=$(echo $JSON_CONTENT | jq -c)" >> "$GITHUB_ENV"


    - name: Run script
      env:
        ACCOUNTS_JSON: ${{ env.ACCOUNTS_JSON }}
        TELEGRAM_JSON: ${{ secrets.TELEGRAM_JSON }}
      run: python run.py

    - name: Commit history files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add history/
        git commit -m "Add cron job results for $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
